const indices = {
  "FD": "Frost Days",
  "SU": "Summer Days",
  "ID": "Ice Days",
  "TR": "Tropical Nights",
  "GSL": "Growing Season Length",
  "TXx": "Maximum of Daily Maximum Temperature",
  "TNx": "Maximum of Daily Minimum Temperature",
  "TXn": "Minimum of Daily Maximum Temperature",
  "TNn": "Minimum of Daily Minimum Temperature",
  "TN10p": "Cold Nights (10th Percentile)",
  "TN90p": "Warm Nights (90th Percentile)",
  "TX10p": "Cool Days (10th Percentile)",
  "TX90p": "Hot Days (90th Percentile)",
  "WSDI": "Warm Spell Duration Indicator",
  "CSDI": "Cold Spell Duration Indicator",
  "DTR": "Daily Temperature Range",
  "ETR": "Extreme Temperature Range",
  "GDDgrown": "Growing Degree Days",
  "HDDheatn": "Heating Degree Days",
  "CDDcoldn": "Cooling Degree Days",
  "CDD": "Consecutive Dry Days",
  "TMge5": "Days with Mean Temp > 5th Percentile",
  "TMge10": "Days with Mean Temp > 10th Percentile",
  "TMlt5": "Days with Mean Temp < 5th Percentile",
  "TMlt10": "Days with Mean Temp < 10th Percentile",
  "TMm": "Mean of Daily Mean Temperature",
  "TXm": "Mean of Daily Maximum Temperature",
  "TNm": "Mean of Daily Minimum Temperature",
  "TXge30": "Days with Max Temp > 30°C",
  "TXge35": "Days with Max Temp > 35°C",
  "TXgt50p": "Days with Max Temp > 50th Percentile",
  "TNlt2": "Days with Min Temp < 2°C",
  "TNltm2": "Days with Min Temp < -2°C",
  "TNltm20": "Days with Min Temp < -20°C",
  "R20mm": "Number of Heavy Precipitation Days",
  "R95p": "Days with Precipitation > 95th Percentile",
  "R99p": "Days with Precipitation > 99th Percentile",
  "R95pTOT": "Contribution from Very Wet Days",
  "R99pTOT": "Contribution from Extremely Wet Days",
  "PRCPTOT": "Annual Total Wet-Day Precipitation",
  "Rx1day": "Max 1-day Precipitation",
  "Rx5day": "Max 5-day Precipitation",
  "SDII": "Simple Daily Intensity Index",
  "SPI": "Standardized Precipitation Index",
  "SPEI": "Standardized Precipitation-Evapotranspiration Index",
  "CWD": "Consecutive Wet Days",
  "HWN": "Heat Wave Number",
  "HWF": "Heat Wave Frequency",
  "HWD": "Heat Wave Duration",
  "HWM": "Heat Wave Magnitude",
  "HWA": "Heat Wave Amplitude",
  "CWN_ECF_ECF": "Cold Wave Number",
  "CWF_ECF": "Cold Wave Frequency",
  "CWD_ECF": "Cold Wave Duration",
  "CWM_ECF": "Cold Wave Magnitude",
  "CWA_ECF": "Cold Wave Amplitude",
};

export function getIndicesNames(abbreviations) {
  return abbreviations.map((abbr) => `${abbr} - ${indices[abbr]}`);
}

export function getIndices() {
  return indices;
}